FROM almalinux:8
ADD hello.txt /tmp/
ADD https://raw.githubusercontent.com/Aparnachamarthi1/dockerfiles/master/COMMANDS.MD/Dockerfile /tmp/C:\devops\daws-74s\repos\dockerfiles\ADD
ADD sample-1.tar /tmp/