FROM almalinux:8
ADD hello.txt /tmp/
ADD https://raw.githubusercontent.com/Aparnachamarthi1/dockerfiles/master/COMMANDS.MD/Dockerfile /tmp/c:\Users\Chamarthi\Downloads\sample-1.tar
ADD sample-1.tar /tmp/